[versions]
androidCore = "1.17.0"
androidGradlePlugin = "8.13.0"
androidTestJunit = "1.3.0"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
espresso = "3.7.0"
glide = "5.0.5"
junit = "4.13.2"
kotlin = "2.2.21"
ksp = "2.3.2"
ktlint = "0.50.0"
material = "1.13.0"
navigation = "2.9.6"
palette = "1.0.0"
spotless = "8.0.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidCore" }
androidx-navigation-navigationFragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-navigationUiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-paletteKtx = { module = "androidx.palette:palette-ktx", version.ref = "palette" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidTestJunit" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }

google-material = { module = "com.google.android.material:material", version.ref = "material" }

junit = { module = "junit:junit", version.ref = "junit" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
navigationSafeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }